### PR TITLE
created a forms.html

### PR DESCRIPTION
**Pull request by hafizkh**
[AB#7](https://dev.azure.com/Hamk-Team4/2c8fea13-3496-4e10-8b29-b3161ec69987/_workitems/edit/7)
This is the file created to input the values like name, phone, email and other inportant information about the voter, so that one can submit this info and updated as vote casted.

### CODE REVIEW

**Comment by imrancsen** [comment]
try to write something more for the description, so it could explain your work more when creating a request.

**Comment by imrancsen** [comment]
try to describe more, when creating requests.

**Comment by hafizkh** [comment]
@imrancsen sure, thanks for reviweing

**Review by imrancsen — APPROVED** [review]
approving for now,
next time be careful ;)

**Comment by hafizkh** [comment]
@imrancsen  ok SIR

**Review by Kasmoi — APPROVED** [review]
after "changes" approved :)

**Pull request merged**
