### PR TITLE
AB#15

### LINKED ISSUE #7: notify_user_cast_vote
[AB#15](https://dev.azure.com/Hamk-Team4/2c8fea13-3496-4e10-8b29-b3161ec69987/_workitems/edit/15)

### PR DESCRIPTION
**Pull request by Kasmoi**
[AB#15](https://dev.azure.com/Hamk-Team4/2c8fea13-3496-4e10-8b29-b3161ec69987/_workitems/edit/15)

notify the user about casting votes

### CODE REVIEW

**Review by hafizkh — APPROVED** [review]
this is ok, approved

**Comment by imrancsen** [comment]
looks good but could please mention the priority somewhere?

**Review by imrancsen — CHANGES_REQUESTED** [review]
please define its priority

**Comment by Kasmoi** [comment]
priority is pretty low since its for further development instead of the initial product

**Review by imrancsen — APPROVED** [review]
ok
approved

**Pull request merged**
