### PR TITLE
AB#16 verifying user through banking credentials

### PR DESCRIPTION
**Pull request by imrancsen**
verification of user through banking credentials

### CODE REVIEW

**Review by Kasmoi — APPROVED** [review]
approved

**Review by hafizkh — COMMENTED** [review]
what exactly you mean for credentials like strong authentication or just google sign up? if it is either of them, which API did you use for it?

**Comment by imrancsen** [comment]
> what exactly you mean for credentials like strong authentication or just google sign up? if it is either of them, which API did you use for it?

it will use banking credentials.

**Comment by hafizkh** [comment]
Then its good

**Review by hafizkh — APPROVED** [review]
approved

**Pull request merged**
